version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: mdschema
    main: ./cmd/mdschema/main.go
    binary: mdschema
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/jackchuka/mdschema/internal/version.Version={{.Version}}
      - -X github.com/jackchuka/mdschema/internal/version.Commit={{.Commit}}
      - -X github.com/jackchuka/mdschema/internal/version.Date={{.Date}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^style:"
      - "^refactor:"
